# Generated by Django 2.2.19 on 2023-04-12 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('id',)},
        ),
    ]
